# Permalinks
permalink:           pretty

# Setup
title:               Matt McCaffrey
tagline:             We gon' be alright...
url:                 https://mmccaff.github.io/
paginate:            5
excerpt_separator:   "<!--excerpt-->"
baseurl:             ""
twitter_username:    mmccaff


# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Matt McCaffrey
  url:               https://twitter.com/mmccaff
  email:             hello@mattmccaffrey.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/mmccaff/mmccaff.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap

plugins:
  - jekyll-sitemap

pages_list:       
  About: '/about'
  Archive: '/archive'

# Optional features
analytics_id: UA-4824740-5
